export const data = [
  {
    _id: "64735282470bf6247b64ac92",
    title: "Plot 1 - Lea Wharf",
    isDeleted: false,
    type: "Apartment",
    address: "The Avenue, Hertford",
    description: "2 bed apartment overlooking the river with balcony",
    feature: "Test",
    listType: "Flat",
    listingPrice: 250000,
    estRentalIncome: 1100,
    developmentNumber: "4564SXZ1",
    titleDeedNumber: "17646cnnn1",
    planPermissionNumber: "3/22/1700/HH1",
    localAuthority: "East Herts",
    internalArea: "100sqm",
    finishQuality: "High",
    numberOfBedrooms: 1,
    constructionDate: "2023-05-23T21:29:09.350Z",
    outdoorSpace: "None",
    numberOfBathrooms: 1,
    googleMapCode: "https://goo.gl/maps/RGi2riXVwnbPY4zQ6",
    offStreetParking: "1 space",
    postalZipCode: "SG23 5TH",
    floorPlan: "https://xcavate.io/assets/LeaWharfFloorPlanProperty-1.pdf",
    salesAgreement: "https://xcavate.io/assets/PropertySaleAgreement.pdf",
    photo1: "https://xcavate.io/assets/LeaWharfProp1-1.jpg",
    photo2: "https://xcavate.io/assets/LeaWharfProp1-2.jpg",
    photo3: "https://xcavate.io/assets/LeaWharfProp1-3.jpg",
    photo4: "https://xcavate.io/assets/LeaWharfProp1-4.jpg",
    company: "https://xcavate.io/assets/chase-new-homes-logo.png",
    dateCreated: "2023-05-28T13:09:22.891Z",
    __v: 0,
  },
  {
    _id: "647352ef470bf6247b64aca4",
    title: "Plot 10 - High View",
    isDeleted: false,
    type: "House",
    address: "The Avenue, New York",
    description: "4 bedroom house",
    feature: "Test",
    listType: "House",
    listingPrice: 1000000,
    estRentalIncome: 5000,
    developmentNumber: "56734DCR3",
    titleDeedNumber: "17646cnnn3",
    planPermissionNumber: "3/22/1700/HH3",
    localAuthority: "New York",
    internalArea: "300sqm",
    finishQuality: "High",
    numberOfBedrooms: 4,
    constructionDate: "2023-05-23T21:29:09.350Z",
    outdoorSpace: "None",
    numberOfBathrooms: 3,
    googleMapCode: "https://goo.gl/maps/2mxMt9deqgBMrf4U7",
    offStreetParking: "1 space",
    postalZipCode: "39175",
    floorPlan: "https://xcavate.io/assets/HighViewFarmFloorPlanProperty-3.pdf",
    salesAgreement: "https://xcavate.io/assets/PropertySaleAgreement.PDF",
    photo1: "https://xcavate.io/assets/HighViewProp3-1.jpg",
    photo2: "https://xcavate.io/assets/HighViewProp3-2.jpg",
    photo3: "https://xcavate.io/assets/HighViewProp3-3.jpg",
    photo4: "https://xcavate.io/assets/HighViewProp3-4.jpg",
    company: "https://xcavate.io/assets/chase-new-homes-logo.png",
    dateCreated: "2023-05-28T13:11:11.046Z",
    __v: 0,
  },
  {
    _id: "647352fe470bf6247b64aca6",
    title: "Plot 11 - High View",
    isDeleted: false,
    type: "House",
    address: "The Avenue, New York",
    description: "3 bedroom house",
    feature: "Test",
    listType: "House",
    listingPrice: 800000,
    estRentalIncome: 3500,
    developmentNumber: "56734DCR4",
    titleDeedNumber: "17646cnnn4",
    planPermissionNumber: "3/22/1700/HH4",
    localAuthority: "New York",
    internalArea: "300sqm",
    finishQuality: "High",
    numberOfBedrooms: 3,
    constructionDate: "2023-05-23T21:29:09.350Z",
    outdoorSpace: "None",
    numberOfBathrooms: 2,
    googleMapCode: "https://goo.gl/maps/2mxMt9deqgBMrf4U7",
    offStreetParking: "1 space",
    postalZipCode: "39175",
    floorPlan: "https://xcavate.io/assets/HighViewFarmFloorPlanProperty-4.PDF",
    salesAgreement: "https://xcavate.io/assets/PropertySaleAgreement.pdf",
    photo1: "https://xcavate.io/assets/HighViewProp4-1.jpg",
    photo2: "https://xcavate.io/assets/HighViewProp4-2.jpg",
    photo3: "https://xcavate.io/assets/HighViewProp4-3.jpg",
    photo4: "https://xcavate.io/assets/HighViewProp4-4.jpg",
    company: "https://xcavate.io/assets/chase-new-homes-logo.png",
    dateCreated: "2023-05-28T13:11:26.289Z",
    __v: 0,
  },
  {
    _id: "647352be470bf6247b64ac94",
    title: "Plot 2 - Lea Wharf",
    isDeleted: false,
    type: "Apartment",
    address: "The Avenue, Hertford",
    description: "3 bed apartment overlooking the river with balcony",
    feature: "Test",
    listType: "Flat",
    listingPrice: 300000,
    estRentalIncome: 1400,
    developmentNumber: "4564SXZ2",
    titleDeedNumber: "17646cnnn2",
    planPermissionNumber: "3/22/1700/HH2",
    localAuthority: "East Herts",
    internalArea: "100sqm",
    finishQuality: "High",
    numberOfBedrooms: 2,
    constructionDate: "2023-05-23T21:29:09.350Z",
    outdoorSpace: "None",
    numberOfBathrooms: 1,
    googleMapCode: "https://goo.gl/maps/RGi2riXVwnbPY4zQ6",
    offStreetParking: "1 space",
    postalZipCode: "SG23 5TH",
    floorPlan: "https://xcavate.io/assets/LeaWharfFloorPlanProperty-2.pdf",
    salesAgreement: "https://xcavate.io/assets/PropertySaleAgreement.pdf",
    photo1: "https://xcavate.io/assets/LeaWharfProp2-1.jpg",
    photo2: "https://xcavate.io/assets/LeaWharfProp2-2.jpg",
    photo3: "https://xcavate.io/assets/LeaWharfProp2-3.jpg",
    photo4: "https://xcavate.io/assets/LeaWharfProp2-4.jpg",
    company: "https://xcavate.io/assets/chase-new-homes-logo.png",
    dateCreated: "2023-05-28T13:10:22.686Z",
    __v: 0,
  },
  {
    _id: "647352c4470bf6247b64ac96",
    title: "Plot 5 - Lancaster House",
    isDeleted: false,
    type: "Apartment",
    address: "The Avenue, North Sydney",
    description: "2 bed apartment in a great location",
    feature: "Test",
    listType: "Apartment",
    listingPrice: 300000,
    estRentalIncome: 1200,
    developmentNumber: "56734DCR5",
    titleDeedNumber: "17646cnnn5",
    planPermissionNumber: "3/22/1700/HH5",
    localAuthority: "North Sydney",
    internalArea: "100sqm",
    finishQuality: "High",
    numberOfBedrooms: 2,
    constructionDate: "2023-05-23T21:29:09.350Z",
    outdoorSpace: "None",
    numberOfBathrooms: 2,
    googleMapCode: "https://goo.gl/maps/syk48AsjFsRB8jmw5",
    offStreetParking: "1 space",
    postalZipCode: "2055",
    floorPlan:
      "https://xcavate.io/assets/LancasterHouseFloorPlanProperty-5.pdf",
    salesAgreement: "https://xcavate.io/assets/PropertySaleAgreement.pdf",
    photo1: "https://xcavate.io/assets/LancasterHouseProp5-1.jpg",
    photo2: "https://xcavate.io/assets/LancasterHouseProp5-2.jpg",
    photo3: "https://xcavate.io/assets/LancasterHouseProp5-3.jpg",
    photo4: "https://xcavate.io/assets/LancasterHouseProp5-4.jpg",
    company: "https://xcavate.io/assets/chase-new-homes-logo.png",
    dateCreated: "2023-05-28T13:10:28.557Z",
    __v: 0,
  },
  {
    _id: "647352ca470bf6247b64ac98",
    title: "Plot 6 - Lancaster House",
    isDeleted: false,
    type: "Apartment",
    address: "The Avenue, North Sydney",
    description: "2 bed apartment in a great location",
    feature: "Test",
    listType: "Apartment",
    listingPrice: 300000,
    estRentalIncome: 1200,
    developmentNumber: "56734DCR5",
    titleDeedNumber: "17646cnnn6",
    planPermissionNumber: "3/22/1700/HH6",
    localAuthority: "North Sydney",
    internalArea: "100sqm",
    finishQuality: "High",
    numberOfBedrooms: 2,
    constructionDate: "2023-05-23T21:29:09.350Z",
    outdoorSpace: "None",
    numberOfBathrooms: 2,
    googleMapCode: "https://goo.gl/maps/syk48AsjFsRB8jmw5",
    offStreetParking: "1 space",
    postalZipCode: "2055",
    floorPlan:
      "https://xcavate.io/assets/LancasterHouseFloorPlanProperty-6.pdf",
    salesAgreement: "https://xcavate.io/assets/PropertySaleAgreement.pdf",
    photo1: "https://xcavate.io/assets/LancasterHouseProp6-1.jpg",
    photo2: "https://xcavate.io/assets/LancasterHouseProp6-2.jpg",
    photo3: "https://xcavate.io/assets/LancasterHouseProp6-3.jpg",
    photo4: "https://xcavate.io/assets/LancasterHouseProp6-4.jpg",
    company: "https://xcavate.io/assets/chase-new-homes-logo.png",
    dateCreated: "2023-05-28T13:10:34.264Z",
    __v: 0,
  },
  {
    _id: "647352cf470bf6247b64ac9a",
    title: "Plot 7 - Williams Court",
    isDeleted: false,
    type: "Apartment",
    address: "Williams Court, North Manchester",
    description: "2 bed apartment in a great location",
    feature: "Test",
    listType: "Apartment",
    listingPrice: 245000,
    estRentalIncome: 1050,
    developmentNumber: "56734DCR7",
    titleDeedNumber: "17646cnnn7",
    planPermissionNumber: "3/22/1700/HH7",
    localAuthority: "Manchester",
    internalArea: "110sqm",
    finishQuality: "High",
    numberOfBedrooms: 2,
    constructionDate: "2023-05-23T21:29:09.350Z",
    outdoorSpace: "None",
    numberOfBathrooms: 2,
    googleMapCode: "https://goo.gl/maps/i2HJnNjECuair6ix8",
    offStreetParking: "1 space",
    postalZipCode: "MC23 8EU",
    floorPlan: "https://xcavate.io/assets/WilliamsCourtFloorPlanProperty-7.pdf",
    salesAgreement: "https://xcavate.io/assets/PropertySaleAgreement.pdf",
    photo1: "https://xcavate.io/assets/WilliamsCourtProp7-1.jpg",
    photo2: "https://xcavate.io/assets/WilliamsCourtProp7-2.jpg",
    photo3: "https://xcavate.io/assets/WilliamsCourtProp7-3.jpg",
    photo4: "https://xcavate.io/assets/WilliamsCourtProp7-4.jpg",
    company: "https://xcavate.io/assets/chase-new-homes-logo.png",
    dateCreated: "2023-05-28T13:10:39.773Z",
    __v: 0,
  },
  {
    _id: "647352d8470bf6247b64ac9c",
    title: "Plot 8 - Williams Court",
    isDeleted: false,
    type: "Apartment",
    address: "Williams Court, North Manchester",
    description: "2 bed apartment in a great location",
    feature: "Test",
    listType: "Apartment",
    listingPrice: 240000,
    estRentalIncome: 1050,
    developmentNumber: "56734DCR8",
    titleDeedNumber: "17646cnnn8",
    planPermissionNumber: "3/22/1700/HH8",
    localAuthority: "Manchester",
    internalArea: "105sqm",
    finishQuality: "High",
    numberOfBedrooms: 2,
    constructionDate: "2023-05-23T21:29:09.350Z",
    outdoorSpace: "None",
    numberOfBathrooms: 2,
    googleMapCode: "https://goo.gl/maps/i2HJnNjECuair6ix8",
    offStreetParking: "1 space",
    postalZipCode: "MC23 8EU",
    floorPlan: "https://xcavate.io/assets/WilliamsCourtFloorPlanProperty-8.pdf",
    salesAgreement: "https://xcavate.io/assets/PropertySaleAgreement.pdf",
    photo1: "https://xcavate.io/assets/WilliamsCourtProp8-1.jpg",
    photo2: "https://xcavate.io/assets/WilliamsCourtProp8-2.jpg",
    photo3: "https://xcavate.io/assets/WilliamsCourtProp8-3.jpg",
    photo4: "https://xcavate.io/assets/WilliamsCourtProp8-4.jpg",
    company: "https://xcavate.io/assets/chase-new-homes-logo.png",
    dateCreated: "2023-05-28T13:10:48.046Z",
    __v: 0,
  },
  {
    _id: "647352dd470bf6247b64ac9e",
    title: "Plot 9 - The Square",
    isDeleted: false,
    type: "Apartment",
    address: "Williams Court, London",
    description: "2 bed apartment in a great location",
    feature: "Test",
    listType: "Apartment",
    listingPrice: 289000,
    estRentalIncome: 1150,
    developmentNumber: "56734DCR9",
    titleDeedNumber: "17646cnnn9",
    planPermissionNumber: "3/22/1700/HH9",
    localAuthority: "London",
    internalArea: "105sqm",
    finishQuality: "High",
    numberOfBedrooms: 2,
    constructionDate: "2023-05-23T21:29:09.350Z",
    outdoorSpace: "None",
    numberOfBathrooms: 2,
    googleMapCode: "https://goo.gl/maps/8QDduF16Z3besf8A6",
    offStreetParking: "1 space",
    postalZipCode: "N45 3LP",
    floorPlan: "https://xcavate.io/assets/TheSquareFloorPlanProperty-9.pdf",
    salesAgreement: "https://xcavate.io/assets/PropertySaleAgreement.pdf",
    photo1: "https://xcavate.io/assets/TheSquareProp9-1.jpg",
    photo2: "https://xcavate.io/assets/TheSquareProp9-2.jpg",
    photo3: "https://xcavate.io/assets/TheSquareProp9-3.jpg",
    photo4: "https://xcavate.io/assets/TheSquareProp9-4.jpg",
    company: "https://xcavate.io/assets/chase-new-homes-logo.png",
    dateCreated: "2023-05-28T13:10:53.292Z",
    __v: 0,
  },
];
