export const data = [
    {
    "_id": "64735282470bf6247b64ac92",
    "title": "Plot 1 - Lea Wharf",
    "isDeleted": false,
    "type": "Flat",
    "address": "The Avenue, Hertford",
    "description": "2 bed apartment overlooking the river with balcony",
    "feature": "Test",
    "listType": "Flat",
    "listingPrice": 250000,
    "estRentalIncome": 1100,
    "developmentNumber": "4564SXZ1",
    "titleDeedNumber": "17646cnnn1",
    "planPermissionNumber": "3/22/1700/HH1",
    "localAuthority": "East Herts",
    "internalArea": "100sqm",
    "finishQuality": "High",
    "numberOfBedrooms": 1,
    "constructionDate": "2023-05-23T21:29:09.350Z",
    "outdoorSpace": "None",
    "numberOfBathrooms": 1,
    "googleMapCode": "https://goo.gl/maps/RGi2riXVwnbPY4zQ6",
    "verificationStatus":"Verified",
    "imageUrl":"https://xcavate.io/assets/LeaWharfProp1-1.jpg",
    "__v": 0
},
{
    "_id": "647352ef470bf6247b64aca4",
    "title": "Plot 2 - Lea Wharf",
    "isDeleted": false,
    "type": "Flat",
    "address": "The Avenue, Hertford",
    "description": "2 bed apartment overlooking the river with balcony",
    "feature": "Test",
    "listType": "Flat",
    "listingPrice": 300000,
    "estRentalIncome": 1400,
    "developmentNumber": "4564SXZ2",
    "titleDeedNumber": "17646cnnn2",
    "planPermissionNumber": "3/22/1700/HH2",
    "localAuthority": "East Herts",
    "internalArea": "100sqm",
    "finishQuality": "High",
    "numberOfBedrooms": 1,
    "constructionDate": "2023-05-23T21:29:09.350Z",
    "outdoorSpace": "None",
    "numberOfBathrooms": 1,
    "googleMapCode": "https://goo.gl/maps/RGi2riXVwnbPY4zQ6",
    "verificationStatus":"Not Verified",
    "imageUrl":"https://xcavate.io/assets/LeaWharfProp2-1.jpg",
    "__v": 0
},
{
    "_id": "647352fe470bf6247b64aca6",
    "title": "Plot 10 - High View",
    "isDeleted": false,
    "type": "Apartment",
    "address": "The Avenue, Hertford",
    "description": "2 bed apartment overlooking the river with balcony",
    "feature": "Test",
    "listType": "Flat",
    "listingPrice": 1000000,
    "estRentalIncome": 5000,
    "developmentNumber": "4564SXZ3",
    "titleDeedNumber": "17646cnnn3",
    "planPermissionNumber": "3/22/1700/HH3",
    "localAuthority": "New York",
    "internalArea": "100sqm",
    "finishQuality": "High",
    "numberOfBedrooms": 4,
    "constructionDate": "2023-05-23T21:29:09.350Z",
    "outdoorSpace": "None",
    "numberOfBathrooms": 3,
    "googleMapCode": "https://goo.gl/maps/2mxMt9deqgBMrf4U7",
    "verificationStatus":"Verified",
    "imageUrl":"https://xcavate.io/assets/HighViewProp3-1.jpg",
    "__v": 0
},
    {
       
        "_id": "647352dd470bf6247b64ac9e",
        "title": "Plot 11 - High View",
        "isDeleted": false,
        "type": "House",
        "address": "The Avenue, New York",
        "description": "2 bed apartment overlooking the river with balcony",
        "feature": "Test",
        "listType": "House",
        "listingPrice": 800000,
        "estRentalIncome": 3500,
        "developmentNumber": "4564SXZ4",
        "titleDeedNumber": "17646cnnn4",
        "planPermissionNumber": "3/22/1700/HH4",
        "localAuthority": "New York",
        "internalArea": "300sqm",
        "finishQuality": "High",
        "numberOfBedrooms": 4,
        "constructionDate": "2023-05-23T21:29:09.350Z",
        "outdoorSpace": "None",
        "numberOfBathrooms": 2,
        "googleMapCode": "https://goo.gl/maps/RGi2riXVwnbPY4zQ6",
        "verificationStatus":"Verified",
        "imageUrl":"https://xcavate.io/assets/HighViewProp4-1.jpg",
        "__v": 0
    },
    {
        "_id": "647352e4470bf6247b64aca0",
        "title": "Plot 5 - Lancaster House",
        "isDeleted": false,
        "type": "Flat",
        "address": "The Avenue, Hertford",
        "description": "2 bed apartment overlooking the river with balcony",
        "feature": "Test",
        "listType": "Flat",
        "listingPrice": 300000,
        "estRentalIncome": 1200,
        "developmentNumber": "4564SXZ5",
        "titleDeedNumber": "17646cnnn5",
        "planPermissionNumber": "3/22/1700/5",
        "localAuthority": "North Sydney",
        "internalArea": "100sqm",
        "finishQuality": "High",
        "numberOfBedrooms": 2,
        "constructionDate": "2023-05-23T21:29:09.350Z",
        "outdoorSpace": "None",
        "numberOfBathrooms": 1,
        "googleMapCode": "https://goo.gl/maps/RGi2riXVwnbPY4zQ6",
        "verificationStatus":"Not Verified",
        "imageUrl":"https://xcavate.io/assets/LancasterHouseProp5-1.jpg",
        "__v": 0
    },
    {
        "_id": "647352e9470bf6247b64aca2",
        "title": "Plot 6 - Lancaster House",
        "isDeleted": false,
        "type": "Flat",
        "address": "The Avenue, Sydney",
        "description": "2 bed apartment overlooking the river with balcony",
        "feature": "Test",
        "listType": "Flat",
        "listingPrice": 300000,
        "estRentalIncome": 1200,
        "developmentNumber": "4564SXZ6",
        "titleDeedNumber": "17646cnnn6",
        "planPermissionNumber": "3/22/1700/HH6",
        "localAuthority": "North Sydney",
        "internalArea": "100sqm",
        "finishQuality": "High",
        "numberOfBedrooms": 1,
        "constructionDate": "2023-05-23T21:29:09.350Z",
        "outdoorSpace": "None",
        "numberOfBathrooms": 1,
        "googleMapCode": "https://goo.gl/maps/RGi2riXVwnbPY4zQ6",
        "verificationStatus":"Listed",
        "imageUrl":"https://xcavate.io/assets/LancasterHouseProp6-1.jpg",
        "__v": 0
    },
    
]